package com.undef.fintrackmobile.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class FintrackBrandColors(
    val celesteBase: Color,
    val celesteSoft: Color,
    val celesteDeep: Color,
    val celestePastel: Color,
    val celestePale: Color,
    val celesteIce: Color,
    val celesteMist: Color,
    val celesteInk: Color,
    val pastelGreenDeep: Color,
    val pastelGreenPale: Color,
    val pastelBlue: Color,
    val pastelRed: Color,
    val pastelGreen: Color,
    val pastelAmber: Color,
    val pastelLilac: Color,
    val indicatorBg: Color,
    val indicatorBorder: Color,
    val offerPeach: Color,
    val offerLavender: Color,
    val offerSand: Color,
    val navBarContainer: Color,
    val navBarSelected: Color,
    val navBarUnselected: Color,
    val navBarIndicator: Color,
    val profileGradientStart: Color,
    val profileGradientEnd: Color,
    val profileAccent: Color,
    val profileLogoutContainer: Color,
    val profileLogoutContent: Color,
    val neutralWhite: Color,
    val neutralBlack: Color,
    val neutralDarkGray: Color,
    val neutralLightGray: Color,
    val neutralTransparent: Color,
    val medalGold: Color,
    val medalSilver: Color,
    val medalBronze: Color,
    val categoryFood: Color,
    val categoryCleaning: Color,
    val categoryHome: Color,
    val categoryOther: Color,
    val supermarketCarrefourBg: Color,
    val supermarketCarrefourAccent: Color,
    val supermarketCotoBg: Color,
    val supermarketCotoAccent: Color,
    val supermarketJumboBg: Color,
    val supermarketJumboAccent: Color,
    val supermarketDefaultBg: Color,
    val supermarketDefaultAccent: Color,
)

val LightBrandColors = FintrackBrandColors(
    celesteBase = CelesteBase,
    celesteSoft = CelesteSoft,
    celesteDeep = CelesteDeep,
    celestePastel = CelestePastel,
    celestePale = CelestePale,
    celesteIce = CelesteIce,
    celesteMist = CelesteMist,
    celesteInk = CelesteInk,
    pastelGreenDeep = PastelGreenDeep,
    pastelGreenPale = PastelGreenPale,
    pastelBlue = PastelBlue,
    pastelRed = PastelRed,
    pastelGreen = PastelGreen,
    pastelAmber = PastelAmber,
    pastelLilac = PastelLilac,
    indicatorBg = IndicatorBg,
    indicatorBorder = IndicatorBorder,
    offerPeach = OfferPeach,
    offerLavender = OfferLavender,
    offerSand = OfferSand,
    navBarContainer = NavBarContainer,
    navBarSelected = NavBarSelected,
    navBarUnselected = NavBarUnselected,
    navBarIndicator = NavBarIndicator,
    profileGradientStart = ProfileGradientStart,
    profileGradientEnd = ProfileGradientEnd,
    profileAccent = ProfileAccent,
    profileLogoutContainer = ProfileLogoutContainer,
    profileLogoutContent = ProfileLogoutContent,
    neutralWhite = NeutralWhite,
    neutralBlack = NeutralBlack,
    neutralDarkGray = NeutralDarkGray,
    neutralLightGray = NeutralLightGray,
    neutralTransparent = NeutralTransparent,
    medalGold = MedalGold,
    medalSilver = MedalSilver,
    medalBronze = MedalBronze,
    categoryFood = PastelBlue,
    categoryCleaning = PastelAmber,
    categoryHome = PastelRed,
    categoryOther = PastelLilac,
    supermarketCarrefourBg = SupermarketCarrefourBg,
    supermarketCarrefourAccent = SupermarketCarrefourAccent,
    supermarketCotoBg = SupermarketCotoBg,
    supermarketCotoAccent = SupermarketCotoAccent,
    supermarketJumboBg = SupermarketJumboBg,
    supermarketJumboAccent = SupermarketJumboAccent,
    supermarketDefaultBg = SupermarketDefaultBg,
    supermarketDefaultAccent = SupermarketDefaultAccent,
)

val LocalFintrackBrandColors = staticCompositionLocalOf { LightBrandColors }

object FintrackTheme {
    val colors: FintrackBrandColors
        @Composable get() = LocalFintrackBrandColors.current
}
